### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by xwmario** [mybbgroup/FancyBox#62]
Getting the error as specified on the post 
https://community.mybb.com/thread-219143-post-1337359.html#pid1337359

**Comment by WildcardSearch** [comment]
Hi, @xwmario 

Thanks for the report. (I am seeing you a lot today 😛 )

When we hear from @Eldenroot, I will get a PR together.

The workaround is to change this line:

https://github.com/mybbgroup/FancyBox/blob/f1c0368f68748a8a6f07f13060381cf3ac530b00/inc/plugins/mybbfancybox.php#L142

to

`'isdefault' => 0`

**Comment by Eldenroot** [comment]
Yeah, this needs to be fixed. Wildcard can you please open a PR? Thx

**Comment by xwmario** [comment]
thankyou for this awesome response 👍
