### ISSUE TITLE
FancyBox on portal and announcements

### ISSUE THREAD

**Issue by MinusPL** [mybbgroup/FancyBox#64]
I know you already have stated that you won't support fancybox on portal.php, but still I don't know why. It would be awesome to have it working there. Is it hard to do, or you just don't want to do it, because you don't use that feature of MyBB?

Also if you open announcement it also has no FancyBox support. It would be nice to have it also there ;)

I like this plugin, it makes going through images much easier and better. Since I want to use portal on my forum based on MyBB I just want to be sure if it isn't going to be supported.
Please if you can consider supporting portal.
If you really don''t want to or simply can't then I will most likely try to add support myself. 🍰

**Comment by Eldenroot** [comment]
@MinusPL - hi! I tried to add it for portal page in past but I had some issues with JS part (not my cup of coffee), so I would like to ask you to send a PR with portal support if you will be successful. I have no problem to add it into FancyBox.

Also if you find any bug let us know.

Thank you buddy

**Comment by MinusPL** [comment]
No problem, I'd try when I have some time. Could you look to announcement part though? If you cannot right now I think I'd try to add it too.

**Comment by Eldenroot** [comment]
Announcements, where? Feel free to add it to.

**Comment by Eldenroot** [comment]
@MinusPL - hi, are you willing to send a PR with that code?

**Comment by SvePu** [comment]
#91 Added portal functionality
