### ISSUE TITLE
Plugin Abandoned ?

### ISSUE THREAD

**Issue by Seeker-Smith** [mybbgroup/FancyBox#65]
Looks like this great plugin has been abandoned which is a shame. Does anyone know how I can change the error message when a user can't access an attachment?

**Comment by Eldenroot** [comment]
You are wrong, it is not abandoned... why do yout thing that? It is fully working and there is no need to release any update soon...

About notification text - check language files in plugin ;)

**Comment by Seeker-Smith** [comment]
Good to hear it's not abandoned however the listed support site mybb.group does not respond.
My question there was "Hi
I found your plugin today and I quite like it. I do have a couple questions.
Do you plan on extending this to the portal?
Can I customize the no permission error you present. "The requested content cannot be loaded. Try again later" .

**Comment by Seeker-Smith** [comment]
And thanks I found the error message that needed to be corrected.

**Comment by Eldenroot** [comment]
I dont use portal page so I will not add a support for this. Anyway you can send a PR with a working code and I will add it into the next release.
