### ISSUE TITLE
Ipad issue

### ISSUE THREAD

**Issue by Dr-The-One** [mybbgroup/FancyBox#66]
On iPad, zoomed image remains static even clicking outside the image. I have to click 'x' to close zoom. - This is an issue.
On PC and Mobile, clicking outside of the zoomed image is closing zoom. - This is perfectly working.

**Comment by Eldenroot** [comment]
Please report directly to the author of the library which is used in this plugin... we cannot fix it in plugin by ourself.

https://github.com/fancyapps/fancybox

**Comment by Eldenroot** [comment]
@lairdshaw - am I right, that this is related to JS library itself? Because we do not change how library works... and I didnt find anything in docs.

**Comment by lairdshaw** [comment]
You're probably right, @Eldenroot, but in any case the upstream author should be able to say for sure.

**Comment by Eldenroot** [comment]
JS-library issue, not the plugin.
