### ISSUE TITLE
Should there be a single gallery for all images on the page?

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/FancyBox#69]
My suggestion: yes, there should be only one image gallery per page.

Currently there are separate galleries, generally (always?) one for each post on the page.

It seems that converting all of these separate galleries into a single gallery would be as simple as setting the `data-fancybox` attribute to a single, constant value everywhere it is used (untested, but based on [the FancyBox documentation](http://fancyapps.com/fancybox/3/docs/#usage)).

**Comment by Eldenroot** [comment]
You are right. This is the way how it was working in past. It was changed because of user's feedback.

I am not against but this should be as an option in ACP. Is that possible? I would be happy if you can open a PR. Thx

**Comment by lairdshaw** [comment]
See what you think of this PR, @Eldenroot (and anybody else).
