### ISSUE TITLE
Add an URL path for "watermark image" into ACP setting

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/FancyBox#83]
Or at least write into description where to upload the image

**Comment by Eldenroot** [comment]
@SvePu - are you available to implement this one? I am thinking about to release a new version soon :) thank you

**Comment by SvePu** [comment]
I'll take a look.

**Comment by SvePu** [comment]
Do you mean something like this:
![fancybox_watermark_image_path](https://user-images.githubusercontent.com/9826631/200644607-3c5f4872-7e85-481a-a3b4-bcbfb14f67e2.png)

**Comment by Eldenroot** [comment]
yes! :)

**Comment by SvePu** [comment]
Pls check #92

**Comment by Eldenroot** [comment]
Done. Thank you
