### ISSUE TITLE
Add css class for watermark image to add possibilities to customization

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/FancyBox#84]
For example display in the bottom right corner of image etc...

**Comment by Eldenroot** [comment]
Maybe something like this could be used (modify a little bit)
`/** FancyBox - vodotisk - watermark **/
.fancybox-slide.watermark .fancybox-spaceball {
	background-image: url('/wiki/watermark_forum.png');
	background-size: 300px 70px;
	background-position: bottom right;
	background-repeat: no-repeat;
	opacity: 0.50;
}

/** FancyBox - vodotisk - hide while scaling (zooming in/out) **/
.fancybox-is-scaling .fancybox-spaceball {
	background-image: none !important;
}`

**Comment by Eldenroot** [comment]
Still thinking about this one

**Comment by SvePu** [comment]
You have to work with CSS:
```CSS
display: absolute;
display: relative;

**Comment by Eldenroot** [comment]
Hmm, yes, so closing this?
