### ISSUE TITLE
"Minimize" feature and "display thumbnails sidebox" conflict

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/FancyBox#85]
When "display thumbnails sidebox" is enabled and you use the minimize button, the sidebox is still displayed 

![image](https://user-images.githubusercontent.com/778890/117692496-5b157400-b1bd-11eb-95f1-3a0f418b2a86.png)

I think it should be hidden on minimize

**Comment by SvePu** [comment]
Add a pr with fix for that ;)
