### ISSUE TITLE
FancyBox library - update to v4?

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/FancyBox#87]
https://fancyapps.com/docs/ui/fancybox/

What do you think, is it possible to update the current one or better to create a new plugin (lite version, without ACP settings) as an Experimental branch?

@lairdshaw 

Btw I do not ask you to do that, because you are busy, but I just would like to know the possibilities. I think the v4 is a complete a new version with different approach etc.

**Comment by lairdshaw** [comment]
As we discussed on Discord, the FancyApps author has confirmed via email that v4 is not free even for open source use (as v3 was/is), so we will not be upgrading to v4. It wouldn't be appropriate for users of our open-source plugin to have to pay for a licence for a library that it includes. I'm belatedly closing this issue.
