### ISSUE TITLE
Support for videos

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/FancyBox#90]
As title says, is that possible?

**Comment by SvePu** [comment]
What kind of videos - embedded or attached ones?

**Comment by Eldenroot** [comment]
Both? But at least for videos in attachments would be nice. Anyway not sure of even possible

**Comment by SvePu** [comment]
I think it isn't kind of easy to integrate this.

**Comment by Eldenroot** [comment]
I agree, lets close this.
