### ISSUE TITLE
Issue with zoom in pages - is possible to solve?

### ISSUE THREAD

**Issue by Eldenroot** [mybbgroup/FancyBox#97]
If you zoom in the page in the thread (mobile phone) -> open any image in attachment -> fancybox is zoomed in too, so you can see only a part of the image - and not even possible to easily zoom out. Is that possible fix, maybe open fancybox with default zoom?

@SvePu

**Comment by SvePu** [comment]
You're right ... did you read this => https://github.com/fancyapps/fancybox/issues/2304

**Comment by Eldenroot** [comment]
Hmm, nope. 

Interesting, is there anything what can be done and do not force users to use this tag?

**Comment by SvePu** [comment]
Don't think so.
