### ISSUE TITLE
The check that a post is being parsed fails in some cases

### ISSUE THREAD

**Issue by lairdshaw** [mybbgroup/FancyBox#99]
In `mybbfancybox_post()` - which hooks into the end of message parsing - we currently check near the top - on line [#501](https://github.com/mybbgroup/FancyBox/blob/v1.2.0/UPLOAD/inc/plugins/mybbfancybox.php#L506) - that the global variable `$post` is not empty, and return immediately if it is. The intent of this check is presumably to make sure that we only modify URLs to be opened by FancyBox within *posts*, and not when some other content is being parsed.

This test, though, sometimes results in false negatives (i.e., scenarios in which we think we're parsing a post but we're not), sometimes resulting in PHP warnings, as, for example, encountered in the wild [here](https://community.mybb.com/thread-219143-post-1384616.html#pid1384616).

Probably even better than the edit I suggested there to line #501:
```php
	if (empty($post) || !is_array($post)) return $message;
```
is:
```php
	if (empty($post['pid'])) return $message;
```

**Comment by Eldenroot** [comment]
Ok, maybe somebody had reported this before on community board?
